PROJECT_NAME = wargame #target file name

CC = gcc #compiler
CFLAGS = -Wall -std=c11 -O3


OBJECTS = main.o restricoes.o pieces.o #objects

all: $(PROJECT_NAME)

$(PROJECT_NAME): $(OBJECTS)
	$(CC) $(CFLAGS) $(OBJECTS) -o $(PROJECT_NAME)

main.o: main.c

restricoes.o: restricoes.c restricoes.h

pieces.o: pieces.c pieces.h


clean:
	rm -f $(PROJECT_NAME) *.o